# netlify.toml - Configuração otimizada para Power BI Service
[build]
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Configurações CORS específicas para Power BI Service
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, HEAD"
    Access-Control-Allow-Headers = "Accept, Accept-Language, Content-Language, Content-Type, Authorization, X-Requested-With, Origin, Referer, User-Agent"
    Access-Control-Expose-Headers = "Content-Length, Content-Range"
    Access-Control-Max-Age = "86400"
    Vary = "Accept-Encoding, Origin"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Headers adicionais para todos os arquivos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"